version: "3.8"

services:
  # -------------------- HDFS NameNode --------------------
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: hdfs-namenode
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://hdfs-namenode:9000
      - HDFS_CONF_dfs_client_use_datanode_hostname=true
    ports:
      - "9871:9870"        # NameNode Web UI (http://localhost:9871)
      - "9000:9000"        # RPC port for Spark/HDFS communication
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    networks:
      - hadoop

  # -------------------- HDFS DataNode --------------------
  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: hdfs-datanode
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://hdfs-namenode:9000
      - HDFS_CONF_dfs_client_use_datanode_hostname=true
      - HDFS_CONF_dfs_datanode_hostname=hdfs-datanode
    ports:
      - "9864:9864"        # DataNode Web UI
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    depends_on:
      - namenode
    networks:
      - hadoop

  # -------------------- Spark Master --------------------
  spark-master:
    image: bde2020/spark-master:3.0.0-hadoop3.2
    container_name: spark-master
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - CORE_CONF_fs_defaultFS=hdfs://hdfs-namenode:9000
      - SPARK_MASTER_HOST=spark-master
    ports:
      - "8080:8080"        # Spark Master UI (http://localhost:8080)
      - "7077:7077"        # Spark Master port
    depends_on:
      - namenode
      - datanode
    networks:
      - hadoop

  # -------------------- Spark Worker --------------------
  spark-worker:
    image: bde2020/spark-worker:3.0.0-hadoop3.2
    container_name: spark-worker
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - CORE_CONF_fs_defaultFS=hdfs://hdfs-namenode:9000
    ports:
      - "8081:8081"        # Spark Worker UI
    depends_on:
      - spark-master
    networks:
      - hadoop

networks:
  hadoop:
    driver: bridge

volumes:
  hadoop_namenode:
  hadoop_datanode:
